USE [master]
GO
/****** Object:  Database [CFD]    Script Date: 19/03/2019 17:09:41 ******/
CREATE DATABASE [CFD]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CFD', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\CFD.mdf' , SIZE = 4288KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'CFD_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\CFD_log.ldf' , SIZE = 1072KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [CFD] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CFD].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [CFD] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [CFD] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [CFD] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [CFD] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [CFD] SET ARITHABORT OFF 
GO
ALTER DATABASE [CFD] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [CFD] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [CFD] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [CFD] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [CFD] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [CFD] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [CFD] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [CFD] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [CFD] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [CFD] SET  ENABLE_BROKER 
GO
ALTER DATABASE [CFD] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [CFD] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [CFD] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [CFD] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [CFD] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [CFD] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [CFD] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [CFD] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [CFD] SET  MULTI_USER 
GO
ALTER DATABASE [CFD] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [CFD] SET DB_CHAINING OFF 
GO
ALTER DATABASE [CFD] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [CFD] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [CFD] SET DELAYED_DURABILITY = DISABLED 
GO
USE [CFD]
GO
/****** Object:  Table [dbo].[__MigrationHistory]    Script Date: 19/03/2019 17:09:41 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[__MigrationHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ContextKey] [nvarchar](300) NOT NULL,
	[Model] [varbinary](max) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK_dbo.__MigrationHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC,
	[ContextKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[People]    Script Date: 19/03/2019 17:09:41 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[People](
	[PersonId] [int] IDENTITY(1,1) NOT NULL,
	[FirstName] [nvarchar](max) NULL,
	[Surname] [nvarchar](max) NULL,
	[Email] [nvarchar](max) NULL,
 CONSTRAINT [PK_dbo.People] PRIMARY KEY CLUSTERED 
(
	[PersonId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

INSERT INTO [dbo].[People] (FirstName) VALUES ('Gencho')
INSERT INTO [dbo].[People] (FirstName)  VALUES ('Conyo')

GO
USE [master]
GO
ALTER DATABASE [CFD] SET  READ_WRITE 
GO
